import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from '@/components';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        style={{
          backgroundImage: 'url(/home_build_bg.svg)',
          backgroundPosition: 'top',
          backgroundSize: 'cover',
          backgroundRepeat: 'no-repeat',
          width: '100vw',
          height: '100vh',
        }}
      >
        <ThemeProvider attribute="class" defaultTheme="root">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
